export const TAKE_DB_DATA='TAKE_DB_DATA';
export const LOG_OUT='LOG_OUT';
export const ADD_ONE_SHOT = 'ADD_ONE_SHOT';
export const REMOVE_ONE_SHOT = 'REMOVE_ONE_SHOT';
export const EDIT_ONE_SHOT = 'EDIT_ONE_SHOT';
export const ADD_STD_EXP = 'ADD_STD_EXP';
export const REMOVE_STD_EXP = 'REMOVE_STD_EXP';
export const EDIT_STD_EXP = 'EDIT_STD_EXP';
export const ADD_SHOPPING_LIST = 'ADD_SHOPPING_LIST';
